added a dye builder (example in CraftyItems)
Raft08/CraftyBuilder pull request #3
Opened 2023-12-27 18:19 UTC by ItsArt3x54

I added a DyeBuilder, its like the ItemBuilder but with 3 news methods.

2024-01-13 17:41 UTC, Raft08 requested changes
Big Thanks for the contribution! I reviewed your code and added some things to change before I can merge it.

2024-01-13 17:41 UTC, Raft08 commented on src/main/java/be/raft/crafty/item/DyeBuilder.java
> +     * Set the color of the dye with a byte
Could you change this line to "Set the color of the dye **using** a byte"

2024-01-13 17:41 UTC, Raft08 commented on src/main/java/be/raft/crafty/item/PotionBuilder.java
> +     * Adds a custom potion effect to this potion
Missing Ponctuation please use '.' at the end of your phrase.

2024-01-13 17:41 UTC, Raft08 commented on src/main/java/be/raft/crafty/item/PotionBuilder.java
> +     * Adds a custom potion effect to this potion
Missing Ponctuation please use '.' at the end of your phrase.

2024-01-13 17:41 UTC, Raft08 commented on src/main/java/be/raft/crafty/item/PotionBuilder.java
> +     * Removes a potion effect from the potion
Missing Ponctuation please use '.' at the end of your phrase.

2024-01-13 17:41 UTC, Raft08 commented on src/main/java/be/raft/crafty/item/PotionBuilder.java
> +     * Moves a potion effect to the top of the potion effect list
Missing Ponctuation please use '.' at the end of your phrase.

2024-01-13 21:01 UTC, Raft08 commented on src/main/java/be/raft/crafty/item/PotionBuilder.java
> +}
Are you sure this is even working? All these function only call themself. Did you test that code

2024-01-14 09:14 UTC, ItsArt3x54 commented
I hadn't test the plugin yet, i'm doing it like tomorrow

2024-01-14 14:45 UTC, Raft08 commented
Please test your code before creating a pull request.

2024-01-15 11:57 UTC, ItsArt3x54 commented
I found a bug with the potions tho, the effect aren't listed in the lore

2024-01-15 18:14 UTC, Raft08 commented
It's not a bug but a feature, so no issues here.

2024-01-15 18:15 UTC, ItsArt3x54 commented
> It's not a bug but a feature, so no issues here.

So why does the setMainEffect exist?

2024-01-15 18:15 UTC, Raft08 approved these changes

2024-01-15 18:16 UTC, Raft08 commented
Alright, Looks good for me. Just let the checks do their job before I merge it.

2024-01-15 18:17 UTC, merged